# Generated by Django 6.0.3 on 2026-04-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_listing_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippinginfo',
            old_name='zipcode',
            new_name='zip_code',
        ),
    ]
